apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-crud-bd
  labels:
    type: local
spec:
  storageClassName: bdstoragecrud
  capacity: 
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
